on:
  pull_request:
    types: [opened, closed]

jobs:
  clubhouse-create:
    runs-on: ubuntu-latest
    steps:
      - uses: singingwolfboy/create-linked-clubhouse-story@closed-merged
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clubhouse-token: ${{ secrets.CLUBHOUSE_TOKEN }}
          project-name: GH Integration Test
          opened-state-name: Reviewing
          merged-state-name: Landed
          closed-state-name: Won't Pursue
