on:
  pull_request:
    types: [opened, reopened]

jobs:
  clubhouse-create:
    runs-on: ubuntu-latest
    steps:
      - uses: singingwolfboy/create-linked-clubhouse-story@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clubhouse-token: ${{ secrets.CLUBHOUSE_TOKEN }}
          project-name: GH Integration Test
          user-map: |
            {
              "singingwolfboy": "5d49d770-ea52-4f7f-986e-402dedb0bbfe"
            }
